services:
    php:
        build:
            dockerfile: ./docker/Dockerfile.php
        container_name: php
        volumes:
            - ./server:/var/www/html
            - ./.env.server:/var/www/html/.env
        networks:
            - laravel
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: demo_laravel
        depends_on:
            - mysql

    supervisor:
        build: 
            context: ./docker
            dockerfile: Dockerfile.supervisor
        ports:
            - "9001:9001"
        volumes:
            - ./supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        networks:
            - laravel

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - 80:80
        volumes: 
            - ./server/public:/var/www/html/public
            - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
            # - ./supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        depends_on: 
            - php
        networks: 
            - laravel
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        tty: true
        volumes: 
            - mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: demo_laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_PASSWORD: secret
        networks: 
            - laravel

networks:
    laravel:

volumes:
    mysql: