services:
    php:
        build:
            dockerfile: ./docker/Dockerfile.php
        container_name: php
        volumes:
            - ./server:/var/www/html
        networks:
            - laravel
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: demo_laravel

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - 8000:80
        volumes: 
            - /server:/var/www/html
            - /nginx/server.conf:/etc/nginx/conf.d/default.conf
            # - ./Docker/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        depends_on: 
            - php
            - mysql
        networks: 
            - laravel
    mysql:
        build: 
            dockerfile: ./docker/Dockerfile.mysql
        container_name: mysql
        restart: unless-stopped
        tty: true
        volumes: 
            - /docker/mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: demo_laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
        networks: 
            - laravel

networks:
    laravel: