services:
    php:
        build:
            context: .
            dockerfile: ./Docker/php/Dockerfile
        container_name: php
        volumes:
            - .:/var/www/html
        networks:
            - laravel
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: demo_laravel

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - 8000:80
        volumes: 
            - .:/var/www/html
            - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks: 
            - laravel
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        tty: true
        volumes: 
            - ./Docker/mysql/data:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: demo_laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
        networks: 
            - laravel

networks:
    laravel: