FROM ubuntu:latest

RUN apt-get update && apt-get install -y openssh-server apache2 supervisor nginx
RUN mkdir -p /var/lock/apache2 /var/run/apache2 /var/run/sshd /var/log/supervisor
RUN echo 'root:password' | chpasswd
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
COPY ./supervisor/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
EXPOSE 22 80 443

CMD ["/usr/bin/supervisord"]